# Generated by Django 4.1.3 on 2023-09-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='services_offered',
            field=models.TextField(null=True),
        ),
    ]
