# Generated by Django 4.1.3 on 2023-09-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='How can we help you?'),
        ),
    ]
