# Generated by Django 4.1.3 on 2023-09-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created_alter_booking_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='info',
            field=models.TextField(null=True, verbose_name='How can we help you?'),
        ),
    ]
