# Generated by Django 4.1.3 on 2023-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='info',
            field=models.TextField(default='', verbose_name='How can we help you?'),
            preserve_default=False,
        ),
    ]
